[tool.poetry]
name = "embeddings"
version = "0.1.0"
authors = ["nystar1", "Pulastya"]
readme = "README.md"
package-mode = false
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.1"
transformers = "^4.53.1"
quart = "^0.20.0"
requests = "^2.32.4"
torch = "^2.7.1"
pillow = "^11.3.0"
python-dotenv = "^1.0.0"
gunicorn = "^23.0.0"

[tool.poetry.scripts]
start = "src.app:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"